### PR TITLE
[BREAKING] Resolve cache access when values are dispatched

### LINKED ISSUE #97: Make load() return cached promises per queue cycle
I'm using DataLoader in combination with GraphQL. The relevant parts of my graph are:

```
Project {
  creator: User!
  memberships: [Membership!]!
}

User {
  id: ID!
  name: String!
}

Membership {
  user: User!
  state: String!
}
```

The resolution behaves like this:

1. Get project
2. Get creator
3. Get memberships (these already include a `userId)`
4. For each member, get its user

User resolution uses a shared DataLoader instance. The creator is also a member. The relative timings are such that by the time I retrieve the user for each member, that instance has already loaded the creator.

As it turns out, I cannot resolve the membership state without also resolving the membership user. Naively I assumed the following would lead to a single batched call to my backend:

```js
async state (membership, variables, context) {
  const someValue = await context.userLoader.load(membership.userId)
  return context.stateLoader.load(someValue)
}
```

However if the creator has already been loaded by the time I call `await context.userLoader.load(membership.userId)`, then a resolved promise is returned. This means that for the creator, `context.stateLoader.load(someValue)` is called much earlier than it is for the other members (since those have to wait on a new `context.userLoader` request). As a result, I have *two* requests to load the state.

The calls to the state resolver happen within the same tick. The problem is that the previous `context.userLoader.load(creatorId)` call leaks into this tick. This would be because the cached promise is returned: https://github.com/facebook/dataloader/blob/25cf990f42f85c4cbffc3a6b55a45df4c0575c6b/src/index.js#L89

I'm proposing that within a tick, calls to `DataLoader#load(key)` with the same `key` return the same promise. Across ticks, they return different promises. All returned promise resolve simultaneously. Once a key is cached, each promise for that key returns the same cached value.

This could be done by maintaining an explicit per-queue cache, which is reset in `dispatchQueue()`.

Let me know if this behavior seems sensible. I can do a PR for it, too.

### PR DESCRIPTION
**Pull request by novemberborn**
When cached keys are loaded along with new keys, make sure the promises
returned for the cached values are resolved in the same micro-task as
those for the newly loaded values.

This means calling code will not (easily) be able to observe whether a
key was cached or not. If calling code uses the values to perform more
loads (perhaps using different data loaders) this ensures that those
loads are combined into a single batch.

In the following example the same loader is used. Without this commit, once
`userLoader.load(1)` is cached, the subsequent loads unexpectedly result in
three requests, not two:

```js
var DataLoader = require('dataloader')

var userLoader = new DataLoader(keys => myBatchGetUsers(keys));

userLoader.load(1)
  .then(firstUser => {
    // Later…

    userLoader.load(1)
      .then(user => userLoader.load(user.invitedByID))
      .then(invitedBy => console.log(`User 1 was invited by ${invitedBy}`));

    // Elsewhere in your application
    userLoader.load(2)
      .then(user => userLoader.load(user.lastInvitedID))
      .then(lastInvited => console.log(`User 2 last invited ${lastInvited}`));
  })
```

This is because `userLoader.load(1)` resolves nearly instantaneously while
`userLoader.load(2)` requires a backend round-trip. This means the subsequent
loads for `user.invitedByID` and `user.lastInvitedID` are not batched together.

*With* this commit however both promises resolve in the same micro-task,
allowing the subsequent loads to be batched.

Fixes #97.

---

This PR is meant to give context to #97.

* I had to use `const` to avoid some Flow ambiguity. Since I don't see it used in the codebase please let me know if that's an issue
* This uses a for..of loop over a `Map`, I hope that's OK
* The cache access promise construction is a bit odd. I'm not too familiar with Flow so please let me know if this can be improved
* There's no tests yet for the new behavior, but existing tests should still pass

The documentation implies that `DataLoader#load()` returns the same promise when caching is enabled. With this PR that changes and promises are only reused while the batch is still enqueued. This is kinda the point of the PR but it might be a considered a breaking change. There are no tests that explicitly guarantee this behavior though.

### CODE REVIEW

**Comment by leebyron** [comment]
This is pretty interesting, thanks for fleshing out an implementation.

It's definitely breaking, seems more like a shift in tradeoffs than an explicit improvement, and adds a lot of implementation complexity. So I'm a bit nervous about proceeding directly

**Comment by novemberborn** [comment]
@leebyron currently DataLoader leaks that a value has been retrieved previously. This makes it harder to reason about its behavior. In my example above it leads to decreased efficiency in subsequent requests.

But yes this is a trade-off, there might be other circumstances where the current behavior leads to better performance. I'd argue it violates the principle of least astonishment though.

**Comment by caub** [comment]
@novemberborn sorry to disturb you, but I don't see where it does 3 requests instead of 2: https://runkit.com/caub/5ab2bdc1a964eb001276b778, or maybe this lib changed since

**Comment by novemberborn** [comment]
@caub in your example the loads aren't racing each other. I think you'll see different behavior if you do `Promise.all([dataloader.load(1), dataloader.load(2)])`. My point in this PR is that you shouldn't be able to observe that `1` has been loaded previously.

**Comment by caub** [comment]
@novemberborn Ah ok, I updated the runkit example, but still can't reproduce

**Comment by novemberborn** [comment]
@caub have a look at this one: https://runkit.com/novemberborn/5ab9142935659d0012049e22

When `1` is loaded it returns immediately (because it was loaded previously), but `2` has an extra delay. If we then load both *again* they both return immediately, as both have been loaded previously.

When used in GraphQL this can prevent requests from being properly batched. Arguably the current behavior is also valid, though.

**Comment by caub** [comment]
@novemberborn Ok, so it behaves as expected, there are no extra requests https://runkit.com/caub/5ab9186d567b6f0012824a7d (you talked about "subsequent loads unexpectedly result in three requests, not two")

I've read #97 as well, I'd be curious to see if you can reproduce this case, it'd help

**Comment by novemberborn** [comment]
> (you talked about "subsequent loads unexpectedly result in three requests, not two")

It can impact batching in GraphQL, in unexpected ways. It's really hard to reason about though.

**Comment by Milan-Popich** [comment]
Copyright Milan Popich all rights reserved

**Pull request closed without merging**
