### PR TITLE
Add typings and test for priming with promise

### LINKED ISSUE #235: [REQUEST] Prime by promise
The issue is with race conditions occurring during fast create and subsequent delete mutations. In short, delete requests can happen much faster than create requests. In long:
- Create request is received by server
- Server sends create request to update state
- Delete request is received by server
- Delete request checks the existence of the entity, but it's not been created yet

It seems like a nice solution would be to `prime` Dataloader's cache with a `Promise` so that the delete request hits this and can `await` the response of the created entity. I.e. either returning the entity, or `undefined`. I tried doing this, but the typings expect the resolved value rather than a `Promise`.

As an alternative, the issue has been somewhat mitigated by client debouncing. It's not fool proof however, and still happens.

### PR DESCRIPTION
**Pull request by LinusU**
This adds typings (for both Flow & TypeScript) and adds a test for priming the cache with a `Promise`

Fixes #235

### CODE REVIEW

**Comment by LinusU** [comment]
@leebyron I've previously signed the CLA for React Native, let me know if there is anything else that is needed to get this landed ☺️

**Comment by LinusU** [comment]
ping @leebyron, is there anything else I can do to facilitate this getting merged?

**Comment by LinusU** [comment]
ping @Caerbannog, are you able to land PRs into this repo? Anything that is needed from my end? ☺️

**Comment by LinusU** [comment]
ping @leebyron would love to get this in, as we still need to use `@ts-ignore` to use this API 😅

**Comment by LinusU** [comment]
@benjie I saw that you approved another pull request, would be able to take a look at this one as well? ☺️

**Comment by koistya** [comment]
@LinusU I assume you may also want to add a unit test with `Promise.reject(...)`

**Comment by benjie** [comment]
No, sorry.

**Comment by LinusU** [comment]
ping @leebyron I would be so happy if this could land 🤩

**Comment by LinusU** [comment]
@leebyron anything I can do to move this forward? Would love to get this released ☺️

**Comment by LinusU** [comment]
@IvanGoncharov I saw that you merged another pull request, would be able to take a look at this one as well? ☺️

**Comment by saihaj** [comment]
Hey @LinusU can you please sign the CLA?

**Comment by LinusU** [comment]
@saihaj awesome to see progress on this! I've signed the CLA now 🚀

**Review by saihaj — APPROVED** [review]

**Comment by saihaj** [comment]
sorry for long wait @LinusU

**Comment by LinusU** [comment]
Thank you for merging! 🙏

**Pull request merged**
